import React from "react";
import { Container, Typography, Box, List, ListItem, ListItemText } from "@mui/material";

export default function Terms() {
  return (
    <Container maxWidth="md" sx={{ py: 4 }}>
      <Typography variant="h4" component="h1" gutterBottom>
        Terms and Conditions
      </Typography>

      <Box sx={{ my: 4 }}>
        <Typography variant="h5" gutterBottom>
          Service Usage
        </Typography>
        <List>
          <ListItem>
            <ListItemText
              primary="Account Responsibility"
              secondary="Users are responsible for maintaining the confidentiality of their account credentials and all activities under their account."
            />
          </ListItem>
          <ListItem>
            <ListItemText
              primary="Acceptable Use"
              secondary="Our services must be used in compliance with all applicable laws and regulations. Users may not use our services for illegal or harmful purposes."
            />
          </ListItem>
        </List>
      </Box>

      <Box sx={{ my: 4 }}>
        <Typography variant="h5" gutterBottom>
          Intellectual Property
        </Typography>
        <List>
          <ListItem>
            <ListItemText
              primary="User Content"
              secondary="Users retain ownership of their content but grant TechMe a license to use, process, and store this content for service provision and improvement."
            />
          </ListItem>
          <ListItem>
            <ListItemText
              primary="AI-Generated Content"
              secondary="Content generated by our AI systems is provided for user use, but TechMe retains certain rights to the underlying technology and algorithms."
            />
          </ListItem>
        </List>
      </Box>

      <Box sx={{ my: 4 }}>
        <Typography variant="h5" gutterBottom>
          Service Limitations
        </Typography>
        <List>
          <ListItem>
            <ListItemText
              primary="Service Availability"
              secondary="We strive for 24/7 service availability but cannot guarantee uninterrupted access. Scheduled maintenance may occur periodically."
            />
          </ListItem>
          <ListItem>
            <ListItemText
              primary="Usage Limits"
              secondary="Service usage may be subject to fair usage policies and technical limitations. Premium features may have additional restrictions."
            />
          </ListItem>
        </List>
      </Box>

      <Box sx={{ my: 4 }}>
        <Typography variant="h5" gutterBottom>
          Payment and Subscription
        </Typography>
        <List>
          <ListItem>
            <ListItemText
              primary="Billing"
              secondary="Subscription fees are billed in advance. Users are responsible for all charges until cancellation of their subscription."
            />
          </ListItem>
          <ListItem>
            <ListItemText
              primary="Refunds"
              secondary="Refund policies vary by subscription type. Please refer to our refund policy for detailed information."
            />
          </ListItem>
        </List>
      </Box>

      <Box sx={{ my: 4 }}>
        <Typography variant="h5" gutterBottom>
          Termination and Suspension
        </Typography>
        <List>
          <ListItem>
            <ListItemText
              primary="Account Termination"
              secondary="Users may terminate their account at any time. TechMe reserves the right to suspend or terminate accounts for violations of these terms."
            />
          </ListItem>
          <ListItem>
            <ListItemText
              primary="Data Retention"
              secondary="Upon account termination, user data will be handled according to our data retention policies and applicable laws."
            />
          </ListItem>
        </List>
      </Box>

      <Box sx={{ my: 4 }}>
        <Typography variant="h5" gutterBottom>
          Liability and Disclaimers
        </Typography>
        <List>
          <ListItem>
            <ListItemText
              primary="Service Warranty"
              secondary="Our services are provided 'as is' without warranties of any kind. We do not guarantee the accuracy or reliability of AI-generated content."
            />
          </ListItem>
          <ListItem>
            <ListItemText
              primary="Limitation of Liability"
              secondary="TechMe shall not be liable for any indirect, incidental, or consequential damages arising from the use of our services."
            />
          </ListItem>
        </List>
      </Box>

      <Box sx={{ my: 4 }}>
        <Typography variant="h5" gutterBottom>
          Changes to Terms
        </Typography>
        <List>
          <ListItem>
            <ListItemText
              primary="Updates"
              secondary="We may modify these terms at any time. Continued use of our services after changes constitutes acceptance of the new terms."
            />
          </ListItem>
          <ListItem>
            <ListItemText
              primary="Notification"
              secondary="Users will be notified of significant changes to these terms through email or platform notifications."
            />
          </ListItem>
        </List>
      </Box>
    </Container>
  );
}
